-- 1. Profiles Table (Users)
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT CHECK (role IN ('admin', 'agent')) NOT NULL,
  name TEXT NOT NULL,
  state TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Inventory Table
CREATE TABLE inventory (
  agent_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (agent_id, product_id)
);

-- 4. Transfers (Waybills) Table
CREATE TABLE transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_agent_id UUID REFERENCES profiles(id),
  destination_agent_id UUID REFERENCES profiles(id),
  product_id BIGINT REFERENCES products(id),
  quantity INTEGER NOT NULL,
  status TEXT CHECK (status IN ('Pending', 'In Transit', 'Delivered')) DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  delivered_at TIMESTAMPTZ
);

-- Enable Row Level Security (RLS)
-- Note: The Express server uses the Service Role Key, which bypasses RLS.
-- If you want to use Supabase directly from the frontend, you'll need to configure these.
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE transfers ENABLE ROW LEVEL SECURITY;

-- Initial Data (Optional - use Bcrypt to generate hashes for real passwords)
-- Admin: admin@logitrack.ng / admin123
-- Agent: abuja@logitrack.ng / agent123
-- Agent: kano@logitrack.ng / agent123
-- Note: The IDs below are placeholders. In a real setup, these would be UUIDs from auth.users.
